### ISSUE TITLE
Update the minified src URL.

### ISSUE THREAD

**Issue by superjose** [caseyyee/aframe-ui-widgets#13]
First of all thank you very much for this amazing component. It's been of great use :D!

It's just a quick heads up to update the URL of the script. It brings a 404 error. 

This would be the correct one:
https://rawgit.com/caseyyee/aframe-ui-widgets/master/dist/aframe-ui-widgets.min.js

**Comment by AndresCuervo** [comment]
Made this tiny change in #14 - please close this issue if that PR goes through, thanks!

**Comment by superjose** [comment]
Sure! Have to remember that, so give me a heads up when it's merged.

**Comment by AndresCuervo** [comment]
@superjose #14 has been merged  :)

**Comment by superjose** [comment]
Beautiful! Thanks a lot for everything!!
